//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATC()
        {
            this.Drugs = new HashSet<Drugs>();
        }
    
        public string ATCCode { get; set; }
        public string RusName { get; set; }
        public string EngName { get; set; }
        public string ParentATCCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drugs> Drugs { get; set; }
    }
}
