//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs_property
    {
        public int id { get; set; }
        public int drug_id { get; set; }
        public int property_id { get; set; }
    
        public virtual Drugs Drugs { get; set; }
        public virtual Property Property { get; set; }
    }
}
