//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Apteka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATC> ATC { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<Drugs_img> Drugs_img { get; set; }
        public virtual DbSet<Drugs_property> Drugs_property { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Sellings> Sellings { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
