//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellings
    {
        public int sell_id { get; set; }
        public int drug_id { get; set; }
        public int count { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> fullprice { get; set; }
    
        public virtual Drugs Drugs { get; set; }
    }
}
